"""Actual MSX execution: menu, supplies, caps, boss choices, records and ending."""
from pathlib import Path
import hashlib,json
from emulator_support import OpenMSX
R=Path(__file__).resolve().parents[2];O=R/'outputs';S=json.loads((R/'work/build/symbols.json').read_text());checks=[]
def check(name,ok,**data):
 print(name,bool(ok),data,flush=True);checks.append(dict(name=name,passed=bool(ok),**data));assert ok,name
for standard in ('ntsc','pal'):
 with OpenMSX(standard,capture=standard=='ntsc',work=R/'work') as e:
  e.load_rom(O/'MIKERO-ODYSSEY.rom','ASCII16');e.run_for(4)
  def get(n,z=1):return e.read_symbol(S,n,z)
  def put(n,v,z=1):e.write_block('memory',S[n],v.to_bytes(z,'little'))
  def tap(k,row=8,wait=.4):
   e.command(f'keymatrixdown {row} {k};after time 0.035 {{keymatrixup {row} {k}}}');e.run_for(wait)
  def tile(x,y,t):e.write_block('memory',S['map']+y*64+x,bytes([t]))
  def room():
   m=bytearray([1]*4096)
   for y in range(5,17):
    for x in range(5,17):m[y*64+x]=0
   e.write_block('memory',S['map'],m)
   for n,v in dict(mode=1,px=10,py=10,hp=20,maxhp=24,level=1,xp=0,attack=3,enemy_count=0,foodclock=0,turns=0,dirty=1,prev_input=0,repeat=0,rescue_pending=0,ending_pending=0).items():put(n,v)
   put('food',400,2);put('turn_count',0,2);e.run_for(.4)
  def counts():return {t:e.read_block('memory',S['map'],4096).count(t) for t in (3,5,6,7)}
  check(standard+'-easy-default',get('mode')==0 and get('difficulty')==0)
  if standard=='ntsc':e.screenshot(O/'title-easy.png',640)
  tap(1,wait=1.8)
  check(standard+'-easy-start',get('depth_max')==15 and get('potion_limit')==9 and get('potions')==3 and get('hp')==24)
  check(standard+'-easy-supplies',counts()=={3:6,5:3,6:15,7:1},counts=counts())
  room();put('hp',5);put('gold',10);tile(11,10,7);tap(128)
  check(standard+'-easy-keeper-full-heal',get('hp')==24 and get('gold')==5 and get('turn_count',2)==0)
  put('hp',5);tap(128);check(standard+'-easy-keeper-reusable',get('hp')==24 and get('gold')==0)
  room();put('hp',5);put('xp',6);put('enemy_count',1);put('ex',11);put('ey',10);put('eh',1);put('et',11);tap(128)
  check(standard+'-easy-level-full-heal',get('level')==2 and get('hp')==26 and get('maxhp')==26)
  room();put('depth',14);tile(11,10,2);tap(128,wait=1.8)
  check(standard+'-easy-final-floor',get('depth')==15 and e.read_block('memory',S['map']+55*64+55,1)==b'\x09')
  bosses=[i for i in range(get('enemy_count')) if e.read_block('memory',S['et']+i,1)==b'\x0f']
  check(standard+'-easy-final-boss',len(bosses)==1 and e.read_block('memory',S['eh']+bosses[0],1)==b'\x18')
  put('px',54);put('py',55);put('enemy_count',0);put('score',1234,2);put('dirty',1);e.run_for(.4)
  e.command('keymatrixdown 8 128;after time 0.035 {keymatrixup 8 128}');e.run_for(.35)
  check(standard+'-ending-before-results',get('mode')==3 and get('ending_pending')==1 and get('ending_phase') in (1,2))
  e.run_for(.1)
  check(standard+'-ending-title-face-planes',e.read_block('VRAM',0x1b00,13)==bytes([127,120,0,15,127,120,4,3,127,120,8,10,208]))
  gfx=(R/'work/build/graphics.bin').read_bytes()
  check(standard+'-ending-title-face-patterns',e.read_block('VRAM',0x3800,96)==gfx[0x1200:0x1260])
  if standard=='ntsc':e.screenshot(O/'gate-closing.png',640)
  e.run_for(2.8)
  check(standard+'-easy-gate-closed',get('mode')==3 and get('ending_pending')==0 and get('ending_phase')==4 and get('score',2)==2734)
  sc=e.read_block('memory',S['screen'],768)
  check(standard+'-easy-result-labels',b'GATE CLOSED!' in sc and b'BEST EASY' in sc and b'15' in sc[320:352] and b'X:TITLE' in sc[736:])
  if standard=='ntsc':e.screenshot(O/'result-easy.png',640)
  tap(32,row=5);check(standard+'-X-title',get('mode')==0)
  tap(128);check(standard+'-normal-selection',get('difficulty')==1)
  e.run_for(1)
  if standard=='ntsc':e.screenshot(O/'title-normal.png',640)
  tap(1,wait=1.8)
  check(standard+'-normal-start',get('depth_max')==30 and get('potion_limit')==5 and get('potions')==2 and get('hp')==24)
  check(standard+'-separate-records',get('high_score',2)==0 and get('best_score',2)==2734)
  check(standard+'-normal-supplies',counts()=={3:4,5:1,6:3,7:1},counts=counts())
  room();put('hp',5);put('maxhp',40);put('gold',30);tile(11,10,7);tap(128)
  check(standard+'-normal-keeper-limited-heal',get('hp')==29 and get('gold')==15 and get('keeper_used')==1)
  put('hp',5);tap(128);check(standard+'-normal-keeper-once',get('hp')==5 and get('gold')==15)
  room();put('potions',5);tile(11,10,3);tap(128)
  check(standard+'-full-pack-preserves-potion',get('potions')==5 and e.read_block('memory',S['map']+651,1)==b'\x03')
  put('hp',5);tap(128,row=5);check(standard+'-normal-potion-12',get('potions')==4 and get('hp')==17)
  tap(16);tap(128);check(standard+'-left-potion-recoverable',get('potions')==5 and e.read_block('memory',S['map']+651,1)==b'\x00')
  room();put('potions',5);put('score',0,2);tile(11,10,5);tap(128)
  check(standard+'-full-pack-chest-leaves-potion',get('score',2)==100 and e.read_block('memory',S['map']+651,1)==b'\x03')
  tap(16);tap(128);check(standard+'-no-repeat-chest-score',get('score',2)==100)
  room();put('hp',5);put('xp',6);put('enemy_count',1);put('ex',11);put('ey',10);put('eh',1);put('et',11);tap(128)
  check(standard+'-normal-level-partial-heal',get('level')==2 and get('hp')==11 and get('maxhp')==26)
  room();put('depth',29);tile(11,10,2);tap(128,wait=1.8)
  check(standard+'-normal-final-floor',get('depth')==30 and get('keeper_used')==0)
  bosses=[i for i in range(get('enemy_count')) if e.read_block('memory',S['et']+i,1)==b'\x0f']
  check(standard+'-normal-boss-endurance',len(bosses)==1 and e.read_block('memory',S['eh']+bosses[0],1)==bytes([96]))
  room();put('depth',30);put('enemy_count',1);put('ex',11);put('ey',10);put('eh',96);put('et',15);put('boss_charge',0);tap(128)
  check(standard+'-boss-telegraph',get('hp')==20 and get('boss_charge')==1 and get('eh')>=92)
  tap(16);check(standard+'-boss-dodge',get('hp')==20 and get('boss_charge')==0 and get('px')==9)
  tap(1);tap(128);check(standard+'-boss-footwork',get('hp')==20 and get('boss_charge')==1)
  tap(1);check(standard+'-boss-ignoring-warning-costs-10',get('hp')==10 and get('boss_charge')==0)
  room();put('depth',30);put('score',5000,2);tile(11,10,9);tap(128,wait=3.5)
  check(standard+'-normal-gate-closed',get('mode')==3 and get('ending_phase')==4 and get('score',2)==8000 and get('high_score',2)==8000)
  sc=e.read_block('memory',S['screen'],768);check(standard+'-normal-result-labels',b'BEST NORMAL' in sc and b'30' in sc[320:352])
  if standard=='ntsc':e.screenshot(O/'result-normal.png',640)
  tap(32,row=5);tap(16);tap(1,wait=1.8);check(standard+'-easy-record-retained',get('difficulty')==0 and get('high_score',2)==2734)
  before=get('turn_count',2);pos=get('music_pos');e.run_for(1)
  psg=e.read_block('PSG regs',0,16)
  check(standard+'-idle-stops-world-and-music',get('turn_count',2)==before and get('music_pos')==pos and psg[9]==0 and psg[10]==0)
  check(standard+'-strict-VRAM',e.timing_violations()==0)
(O/'difficulty-verification.json').write_text(json.dumps(dict(rom_sha256=hashlib.sha256((O/'MIKERO-ODYSSEY.rom').read_bytes()).hexdigest(),checks=checks,method='Controlled RAM scenes with real keyboard input, NTSC/PAL MSX1 RAM32K VRAM16K; screenshots from native emulator.'),indent=2))
